#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleDbFiller
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PeopleFinder")]
	public partial class PersonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPerson(Person instance);
    partial void UpdatePerson(Person instance);
    partial void DeletePerson(Person instance);
    #endregion
		
		public PersonDataContext() : 
				base(global::PeopleDbFiller.Properties.Settings.Default.PeopleFinderConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public PersonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Person> Persons
		{
			get
			{
				return this.GetTable<Person>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persons")]
	public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MisparIshi;
		
		private string _WorkPhone;
		
		private string _GivenName;
		
		private string _JobTitle;
		
		private string _Location;
		
		private string _LongWorkTitle;
		
		private string _AlternateName;
		
		private string _Department;
		
		private string _Company;
		
		private string _Mobile;
		
		private string _Mail;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _Surname;
		
		private string _Darga;
		
		private string _Sex;
		
		private string _BirthdayDisplayString;
		
		private string _JobTitleSearchable;
		
		private string _LongWorkTitleSearchable;
		
		private string _AlternateNameSearchable;
		
		private string _DepartmentSearchable;
		
		private string _CompanySearchable;
		
		private System.Nullable<long> _Tags;
		
		private string _OtherTelephone;
		
		private string _Fax;
		
		private string _HomeTelephone;
		
		private string _WhatIDo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMisparIshiChanging(string value);
    partial void OnMisparIshiChanged();
    partial void OnWorkPhoneChanging(string value);
    partial void OnWorkPhoneChanged();
    partial void OnGivenNameChanging(string value);
    partial void OnGivenNameChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnLongWorkTitleChanging(string value);
    partial void OnLongWorkTitleChanged();
    partial void OnAlternateNameChanging(string value);
    partial void OnAlternateNameChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnPictureChanging(System.Data.Linq.Binary value);
    partial void OnPictureChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnDargaChanging(string value);
    partial void OnDargaChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnBirthdayDisplayStringChanging(string value);
    partial void OnBirthdayDisplayStringChanged();
    partial void OnJobTitleSearchableChanging(string value);
    partial void OnJobTitleSearchableChanged();
    partial void OnLongWorkTitleSearchableChanging(string value);
    partial void OnLongWorkTitleSearchableChanged();
    partial void OnAlternateNameSearchableChanging(string value);
    partial void OnAlternateNameSearchableChanged();
    partial void OnDepartmentSearchableChanging(string value);
    partial void OnDepartmentSearchableChanged();
    partial void OnCompanySearchableChanging(string value);
    partial void OnCompanySearchableChanged();
    partial void OnTagsChanging(System.Nullable<long> value);
    partial void OnTagsChanged();
    partial void OnOtherTelephoneChanging(string value);
    partial void OnOtherTelephoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnHomeTelephoneChanging(string value);
    partial void OnHomeTelephoneChanged();
    partial void OnWhatIDoChanging(string value);
    partial void OnWhatIDoChanged();
    #endregion
		
		public Person()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MisparIshi", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MisparIshi
		{
			get
			{
				return this._MisparIshi;
			}
			set
			{
				if ((this._MisparIshi != value))
				{
					this.OnMisparIshiChanging(value);
					this.SendPropertyChanging();
					this._MisparIshi = value;
					this.SendPropertyChanged("MisparIshi");
					this.OnMisparIshiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPhone", DbType="VarChar(255)")]
		public string WorkPhone
		{
			get
			{
				return this._WorkPhone;
			}
			set
			{
				if ((this._WorkPhone != value))
				{
					this.OnWorkPhoneChanging(value);
					this.SendPropertyChanging();
					this._WorkPhone = value;
					this.SendPropertyChanged("WorkPhone");
					this.OnWorkPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this.OnGivenNameChanging(value);
					this.SendPropertyChanging();
					this._GivenName = value;
					this.SendPropertyChanged("GivenName");
					this.OnGivenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="VarChar(255)")]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this.OnJobTitleChanging(value);
					this.SendPropertyChanging();
					this._JobTitle = value;
					this.SendPropertyChanged("JobTitle");
					this.OnJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(255)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongWorkTitle", DbType="VarChar(255)")]
		public string LongWorkTitle
		{
			get
			{
				return this._LongWorkTitle;
			}
			set
			{
				if ((this._LongWorkTitle != value))
				{
					this.OnLongWorkTitleChanging(value);
					this.SendPropertyChanging();
					this._LongWorkTitle = value;
					this.SendPropertyChanged("LongWorkTitle");
					this.OnLongWorkTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternateName", DbType="VarChar(255)")]
		public string AlternateName
		{
			get
			{
				return this._AlternateName;
			}
			set
			{
				if ((this._AlternateName != value))
				{
					this.OnAlternateNameChanging(value);
					this.SendPropertyChanging();
					this._AlternateName = value;
					this.SendPropertyChanged("AlternateName");
					this.OnAlternateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(255)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(255)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(255)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(255)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Darga", DbType="VarChar(255)")]
		public string Darga
		{
			get
			{
				return this._Darga;
			}
			set
			{
				if ((this._Darga != value))
				{
					this.OnDargaChanging(value);
					this.SendPropertyChanging();
					this._Darga = value;
					this.SendPropertyChanged("Darga");
					this.OnDargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="VarChar(255)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthdayDisplayString", DbType="VarChar(5)")]
		public string BirthdayDisplayString
		{
			get
			{
				return this._BirthdayDisplayString;
			}
			set
			{
				if ((this._BirthdayDisplayString != value))
				{
					this.OnBirthdayDisplayStringChanging(value);
					this.SendPropertyChanging();
					this._BirthdayDisplayString = value;
					this.SendPropertyChanged("BirthdayDisplayString");
					this.OnBirthdayDisplayStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleSearchable", DbType="VarChar(255)")]
		public string JobTitleSearchable
		{
			get
			{
				return this._JobTitleSearchable;
			}
			set
			{
				if ((this._JobTitleSearchable != value))
				{
					this.OnJobTitleSearchableChanging(value);
					this.SendPropertyChanging();
					this._JobTitleSearchable = value;
					this.SendPropertyChanged("JobTitleSearchable");
					this.OnJobTitleSearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongWorkTitleSearchable", DbType="VarChar(255)")]
		public string LongWorkTitleSearchable
		{
			get
			{
				return this._LongWorkTitleSearchable;
			}
			set
			{
				if ((this._LongWorkTitleSearchable != value))
				{
					this.OnLongWorkTitleSearchableChanging(value);
					this.SendPropertyChanging();
					this._LongWorkTitleSearchable = value;
					this.SendPropertyChanged("LongWorkTitleSearchable");
					this.OnLongWorkTitleSearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternateNameSearchable", DbType="VarChar(255)")]
		public string AlternateNameSearchable
		{
			get
			{
				return this._AlternateNameSearchable;
			}
			set
			{
				if ((this._AlternateNameSearchable != value))
				{
					this.OnAlternateNameSearchableChanging(value);
					this.SendPropertyChanging();
					this._AlternateNameSearchable = value;
					this.SendPropertyChanged("AlternateNameSearchable");
					this.OnAlternateNameSearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentSearchable", DbType="VarChar(255)")]
		public string DepartmentSearchable
		{
			get
			{
				return this._DepartmentSearchable;
			}
			set
			{
				if ((this._DepartmentSearchable != value))
				{
					this.OnDepartmentSearchableChanging(value);
					this.SendPropertyChanging();
					this._DepartmentSearchable = value;
					this.SendPropertyChanged("DepartmentSearchable");
					this.OnDepartmentSearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySearchable", DbType="VarChar(255)")]
		public string CompanySearchable
		{
			get
			{
				return this._CompanySearchable;
			}
			set
			{
				if ((this._CompanySearchable != value))
				{
					this.OnCompanySearchableChanging(value);
					this.SendPropertyChanging();
					this._CompanySearchable = value;
					this.SendPropertyChanged("CompanySearchable");
					this.OnCompanySearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="BigInt")]
		public System.Nullable<long> Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this.OnTagsChanging(value);
					this.SendPropertyChanging();
					this._Tags = value;
					this.SendPropertyChanged("Tags");
					this.OnTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherTelephone", DbType="VarChar(255)")]
		public string OtherTelephone
		{
			get
			{
				return this._OtherTelephone;
			}
			set
			{
				if ((this._OtherTelephone != value))
				{
					this.OnOtherTelephoneChanging(value);
					this.SendPropertyChanging();
					this._OtherTelephone = value;
					this.SendPropertyChanged("OtherTelephone");
					this.OnOtherTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(255)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeTelephone", DbType="VarChar(255)")]
		public string HomeTelephone
		{
			get
			{
				return this._HomeTelephone;
			}
			set
			{
				if ((this._HomeTelephone != value))
				{
					this.OnHomeTelephoneChanging(value);
					this.SendPropertyChanging();
					this._HomeTelephone = value;
					this.SendPropertyChanged("HomeTelephone");
					this.OnHomeTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhatIDo", DbType="VarChar(255)")]
		public string WhatIDo
		{
			get
			{
				return this._WhatIDo;
			}
			set
			{
				if ((this._WhatIDo != value))
				{
					this.OnWhatIDoChanging(value);
					this.SendPropertyChanging();
					this._WhatIDo = value;
					this.SendPropertyChanged("WhatIDo");
					this.OnWhatIDoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
